version: 2
updates:
  # Main project
  - package-ecosystem: swift
    directory: "/"
    schedule:
      interval: weekly
      time: "01:00"
    open-pull-requests-limit: 20
    labels:
      - "dependencies"
      - "automerge"
    commit-message:
      prefix: "chore"
