name: Swift

on: [pull_request]

jobs:
  build-test:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        swift: [ "5.5", "5.10" ]
    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift }}
      - name: Get swift version
        run: swift --version
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
  lint:
    name: Swift Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: norio-nomura/action-swiftlint@3.2.1